Sanchezjang/ks43team01

ks43team01/src/main/java/ks43team01/admin/controller/AdminOrderController.java
ks43team01/src/main/java/ks43team01/dto/OrderCurrentStatus.java
ks43team01/src/main/java/ks43team01/mapper/OrderMapper.java
ks43team01/src/main/java/ks43team01/service/OrderService.java
ks43team01/src/main/resources/mapper/OrderMapper.xml
ks43team01/src/main/resources/templates/adminpage/orderAdmin/addOrderStatusStandard.html
ks43team01/src/main/resources/templates/adminpage/orderAdmin/orderCurrentStatusList.html

orderStatusStandard 기준 조회

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminOrderCancelController.java
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/order/orderCancel.html
ks43team01/src/main/resources/templates/adminpage/order/orderRefund.html
ks43team01/src/main/resources/templates/adminpage/user/sellerdetails.html
ks43team01/src/main/resources/templates/adminpage/user/userAgreeCheck.html
ks43team01/src/main/resources/templates/adminpage/user/userAgreeDatails.html

레프트메뉴 고고고고

---

ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html

left 메뉴 추가 (orderStatus)

---

ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewDetail.html
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html

리뷰 상세페이지 생성

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPaymentController.java
ks43team01/src/main/java/ks43team01/mapper/PaymentMapper.java
ks43team01/src/main/java/ks43team01/service/PaymentService.java
ks43team01/src/main/resources/mapper/paymentMapper.xml
ks43team01/src/main/resources/templates/adminpage/payment/paymentInfo.html
ks43team01/src/main/resources/templates/adminpage/payment/paymentList.html

결제 상세내역 보기 기능 추가

---

ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewDetail.html

리뷰(포인트내역, 회원테이블) 포인트  적립 생성

---

ks43team01/src/main/java/ks43team01/dto/Goods.java
ks43team01/src/main/java/ks43team01/dto/GoodsImage.java
ks43team01/src/main/java/ks43team01/dto/GoodsPriceSetting.java
ks43team01/src/main/java/ks43team01/dto/GoodsRequest.java
ks43team01/src/main/java/ks43team01/dto/GoodsSubCategory.java
ks43team01/src/main/java/ks43team01/dto/GoodsTopCategory.java
ks43team01/src/main/java/ks43team01/mapper/GoodsMapper.java
ks43team01/src/main/java/ks43team01/mapper/UserMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsService.java
ks43team01/src/main/java/ks43team01/service/UserService.java
ks43team01/src/main/java/ks43team01/user/controller/MainController.java
ks43team01/src/main/java/ks43team01/user/controller/UserController.java
ks43team01/src/main/java/ks43team01/user/controller/UserGoodsController.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml
ks43team01/src/main/resources/templates/userpage/goods/userGoodsList.html

Goods 등등 생성

---

ks43team01/src/main/java/ks43team01/user/controller/UserGoodsController.java

어려울거라고 몰랐어

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminOrderController.java
ks43team01/src/main/java/ks43team01/mapper/OrderMapper.java
ks43team01/src/main/java/ks43team01/service/OrderService.java
ks43team01/src/main/java/ks43team01/user/controller/OrderController.java
ks43team01/src/main/resources/mapper/OrderMapper.xml
ks43team01/src/main/resources/templates/adminpage/orderAdmin/orderCurrentStatusInfo.html
ks43team01/src/main/resources/templates/adminpage/orderAdmin/orderCurrentStatusList.html
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html

20220624 05:24 주문 폼 추가

---

ks43team01/src/main/java/ks43team01/dto/Goods.java
ks43team01/src/main/java/ks43team01/dto/ReviewContentsReg.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml

Jangsanghyeok

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminReviewController.java
ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointGradeList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html
ks43team01/src/main/resources/templates/adminpage/reviewAdmin/reviewAdminList.html

포인트, 리뷰 쪽 수정삭제 업데이트

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminGoodsAllController.java
ks43team01/src/main/java/ks43team01/admin/controller/AdminProfitAndLossController.java
ks43team01/src/main/java/ks43team01/mapper/GoodsAllMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsAllService.java
ks43team01/src/main/resources/mapper/GoodsAllMapper.xml
ks43team01/src/main/resources/templates/adminpage/goods/addGoodsSubCategory.html
ks43team01/src/main/resources/templates/adminpage/goods/addGoodsTopCategory.html
ks43team01/src/main/resources/templates/adminpage/goods/adminGoodsList.html
ks43team01/src/main/resources/templates/adminpage/goods/removeAdminGoods.html
ks43team01/src/main/resources/templates/adminpage/goods/removeGoodsSubCategory.html
ks43team01/src/main/resources/templates/adminpage/goods/removeGoodsTopCategory.html
ks43team01/src/main/resources/templates/userpage/goods/addGoods.html

상품 관리자 화면 추가

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/boardDetail.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html

board 상세보기

---

ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/boardDetail.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/modifyBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html
ks43team01/src/main/resources/templates/userpage/fragments/header.html

board header 경로 추가

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/admin/controller/AdminReviewController.java
ks43team01/src/main/java/ks43team01/dto/PointSaveByGrade.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointGradeList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html
ks43team01/src/main/resources/templates/adminpage/reviewAdmin/reviewAdminList.html

포인트 , 리뷰 삭제 처리 레프트메뉴 포인트 등록 추가

포인트 , 리뷰 삭제 처리 레프트메뉴 포인트 등록 추가

---

ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/addpointGradeList.html

pointGradeRegList -> addPointGradeList 로 변경

pointGradeRegList -> addPointGradeList 로 변경

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addFreeBoard.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/modifyFaqBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyFreeBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html

2022-06-27 (17:27) board 수정 삭제 추가

2022-06-27 (17:27) board 수정 삭제 추가

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/addPointGradeList.html

포인트 기준 등록 생성

---

ks43team01/src/main/java/ks43team01/user/controller/LoginController.java
ks43team01/src/main/java/ks43team01/user/controller/OrderCartController.java
ks43team01/src/main/java/ks43team01/user/controller/UserController.java
ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html
ks43team01/src/main/resources/templates/userpage/order/orderCart.html
ks43team01/src/main/resources/templates/userpage/user/login.html

오전 시작 커밋!!!! 주문 페이지 데이터 받아오는 처리

오전 시작 커밋!!!! 주문 페이지 데이터 받아오는 처리

---

ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/user/login.html

로그인 @Request에러해결

---

ks43team01/src/main/resources/templates/userpage/order/orderCart.html
ks43team01/src/main/resources/templates/userpage/user/userinfomation.html

user info 수정

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminBoardController.java
ks43team01/src/main/java/ks43team01/dto/BoardAnswer.java
ks43team01/src/main/java/ks43team01/dto/BoardComment.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/adminpage/boardAdmin/boardAnswerList.html
ks43team01/src/main/resources/templates/adminpage/boardAdmin/boardCommentList.html
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardDetail.html

2022-06-28(11:42) adminpage leftmenu boardComment, boardAnswer 경로 추가

---

ks43team01/src/main/java/ks43team01/user/controller/OrderCartController.java
ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html
ks43team01/src/main/resources/templates/userpage/order/orderCart.html
ks43team01/src/main/resources/templates/userpage/order/orderSuccess.html

Sanchezjang

---

ks43team01/src/main/java/ks43team01/dto/BoardAnswer.java
ks43team01/src/main/java/ks43team01/dto/BoardComment.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/adminpage/boardAdmin/boardAnswerList.html
ks43team01/src/main/resources/templates/adminpage/boardAdmin/boardCommentList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardDetail.html

2022-06-28 (17:36) boardComment 수정 진행

---

ks43team01/src/main/java/ks43team01/mapper/GoodsMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsService.java
ks43team01/src/main/java/ks43team01/user/controller/UserGoodsController.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml
ks43team01/src/main/resources/templates/userpage/goods/addGoods.html
ks43team01/src/main/resources/templates/userpage/goods/goodsInfo.html
ks43team01/src/main/resources/templates/userpage/goods/modifyGoodsInfo.html

상품 카테고리 다중 셀렉트박스 수정

---

ks43team01/src/main/resources/templates/userpage/goods/modifyGoodsInfo.html

상품 수정 화면 셀렉트박스 옵션 값 가져오기 작업중

---

ks43team01/src/main/java/ks43team01/dto/OrderCurrent.java
ks43team01/src/main/java/ks43team01/dto/OrderStatusComplete.java
ks43team01/src/main/java/ks43team01/mapper/OrderCartMapper.java
ks43team01/src/main/java/ks43team01/service/OrderCartService.java
ks43team01/src/main/java/ks43team01/user/controller/OrderCartController.java
ks43team01/src/main/resources/mapper/OrderCartMapper.xml
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html
ks43team01/src/main/resources/templates/userpage/order/orderSuccess.html

퇴근커밋 결제 하고 안내메세지와최동 이동까지 완료

---

ks43team01/src/main/java/ks43team01/dto/Board.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardDetail.html

2022-06-30(17:33) board 댓글 삭제 추가

---

ks43team01/src/main/resources/templates/userpage/board/qnaBoardDetail.html

board commit

---

ks43team01/src/main/java/ks43team01/dto/Board.java
ks43team01/src/main/java/ks43team01/dto/QnaBoard.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardList.html

2022-07-04 (17:25) QnaBoard 게시글 등록 수정

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminGoodsController.java
ks43team01/src/main/java/ks43team01/mapper/GoodsMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsService.java
ks43team01/src/main/java/ks43team01/user/controller/UserGoodsController.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml
ks43team01/src/main/resources/templates/adminpage/goods/goodsSubCategoryList.html
ks43team01/src/main/resources/templates/adminpage/goods/modifyGoodsSubCategory.html
ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/goods/modifyGoodsInfo.html

상품 하위 카테고리 수정 추가

---

ks43team01/src/main/java/ks43team01/dto/BoardMediumCategory.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html

2022-07-05 (17:18) board large, medium category

---

ks43team01/src/main/java/ks43team01/dto/RefundPayment.java
ks43team01/src/main/java/ks43team01/dto/UserAgree.java
ks43team01/src/main/java/ks43team01/dto/UserAgreeDetails.java
ks43team01/src/main/java/ks43team01/mapper/PaymentRefundMapper.java
ks43team01/src/main/java/ks43team01/service/PaymentRefundService.java
ks43team01/src/main/java/ks43team01/user/controller/OrderCancleController.java
ks43team01/src/main/resources/mapper/OrderCancleMapper.xml
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html
ks43team01/src/main/resources/templates/userpage/order/orderCancel.html

환불 40%완성커밋 내일 100%완료예

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/dto/PointSaveByGrade.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/templates/adminpage/pointDetails/addPointGradeList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointGradeList.html

포인트 기능 등록 완성

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/adminpage/pointDetails/modifyGradeList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointGradeList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html
ks43team01/src/main/resources/templates/adminpage/reviewAdmin/reviewAdminList.html
ks43team01/src/main/resources/templates/userpage/reviewUser/modifyReview.html
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html
ks43team01/src/main/resources/templates/userpage/user/userinfomation.html

중간 커밋(오류 충돌 방지)

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminUserController.java
ks43team01/src/main/java/ks43team01/mapper/UserMapper.java
ks43team01/src/main/java/ks43team01/service/UserService.java
ks43team01/src/main/resources/mapper/UserMapper.xml
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/user/userAgreeCheck.html

퇴근커밋!!!! admin작업 거의 끝남! 회원 테이블

퇴근커밋!!!! admin작업 거의 끝남! 회원 테이블

---

ks43team01/src/main/java/ks43team01/dto/QnaBoard.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardList.html

2022-07-06 (17:23) 1:1 board 등록 추가

---

ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/application.properties
ks43team01/src/main/resources/log4jdbc.log4j2.properties
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/userpage/reviewUser/addReview.html
ks43team01/src/main/resources/templates/userpage/user/userinfomation.html

장바구니 리뷰 쓰기와 리뷰 등록 (화면,기능) 연결

---

ks43team01/pom.xml
ks43team01/src/main/java/ks43team01/common/FileUtils.java
ks43team01/src/main/java/ks43team01/mapper/FileMapper.java
ks43team01/src/main/resources/application.properties
ks43team01/src/main/resources/log4jdbc.log4j2.properties

2022-07-07 (16:22) 배포 에러 수정 및 파일 처리

---

ks43team01/src/main/resources/templates/adminpage/fragments/searchBar.html
ks43team01/src/main/resources/templates/adminpage/reviewAdmin/reviewAdminList.html
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html

searchBar 프래그먼트 생성을 위한 틀 생성

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminGoodsController.java
ks43team01/src/main/java/ks43team01/mapper/GoodsMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsService.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml
ks43team01/src/main/resources/templates/adminpage/goods/goodsTopCategoryList.html
ks43team01/src/main/resources/templates/adminpage/goods/modifyGoodsTopCategory.html

상품 상위 카테고리 수정 추가

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminOrderCancelController.java
ks43team01/src/main/java/ks43team01/dto/User.java
ks43team01/src/main/resources/mapper/UserMapper.xml
ks43team01/src/main/resources/templates/adminpage/orderCancel/orderCancel.html
ks43team01/src/main/resources/templates/userpage/user/userinfomation.html

환불80%완료 커밋

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/dto/ReviewContentsReg.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/adminpage/fragments/searchBar.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html
ks43team01/src/main/resources/templates/userpage/reviewUser/addReview.html

배포용 커밋(검색기능 추가-미완)

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminBoardController.java
ks43team01/src/main/java/ks43team01/common/FileUtils.java
ks43team01/src/main/java/ks43team01/dto/File.java
ks43team01/src/main/java/ks43team01/dto/QnaBoard.java
ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/mapper/FileMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/mapper/FileMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardDetail.html

2022-07-08 (16:16) common 파일 첨부 등록 기능

---

ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/application.properties
ks43team01/src/main/resources/log4jdbc.log4j2.properties
ks43team01/src/main/resources/logback-spring.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml

log4jdbc 수정

---

ks43team01/src/main/java/ks43team01/dto/QnaBoard.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml

2022-07-11 (10:56) 1:1 등록 추가

---

ks43team01/src/main/java/ks43team01/dto/Board.java
ks43team01/src/main/resources/mapper/BoardMapper.xml

2022-07-11 (17:27) 페이지 수 추가중

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/adminpage/fragments/leftmenu.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/addPointList.html
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html

포인트 리뷰 쪽 수정 중(배포커밋), 포인트 기준 등록 오류 수정

포인트 리뷰 쪽 수정 중(배포커밋), 포인트 기준 등록 오류 수정

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml

2022-07-12 (17:21) board 들여쓰기

---

ks43team01/src/main/java/ks43team01/mapper/GoodsMapper.java
ks43team01/src/main/java/ks43team01/service/GoodsService.java
ks43team01/src/main/java/ks43team01/user/controller/MainController.java
ks43team01/src/main/java/ks43team01/user/controller/UserGoodsController.java
ks43team01/src/main/resources/mapper/GoodsMapper.xml
ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/goods/goodsInfo.html
ks43team01/src/main/resources/templates/userpage/goods/userGoodsList.html

메인화면 상품카테고리 클릭 시 카테고리별 리스트 출력 (추가)

메인화면 상품카테고리 클릭 시 카테고리별 리스트 출력 (추가)

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml

2022-07-13 (16:42) board 조회수 증가 추가

---

ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/static/admin/build/css/datepicker.css
ks43team01/src/main/resources/static/admin/vendors/jquery/dist/searchDate.js
ks43team01/src/main/resources/templates/adminpage/pointDetails/pointList.html

리뷰 등록하면 포인트 내역에 쌓이는 기능 완료 , 기간별 검색 (달력만 추가)

리뷰 등록하면 포인트 내역에 쌓이는 기능 완료 , 기간별 검색 기능 (

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/java/ks43team01/mapper/PointMapper.java
ks43team01/src/main/java/ks43team01/service/PointService.java
ks43team01/src/main/resources/static/assets/css/style.css
ks43team01/src/main/resources/templates/userpage/fragments/head.html

유저페이지 폰트변경(주아체)

---

ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addFaqBoard.html
ks43team01/src/main/resources/templates/userpage/board/addFreeBoard.html
ks43team01/src/main/resources/templates/userpage/board/addNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/addQnaBoardReply.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/modifyFaqBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyFreeBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardDetail.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardList.html
ks43team01/src/main/resources/templates/userpage/order/addOrderCurrentStatus.html

2022-07-14 (16:28) 1:1 문의게시글 자동 답변 완료

---

ks43team01/src/main/java/ks43team01/admin/controller/AdminPointController.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/static/assets/css/style.css
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html

2022.07.14(16:30) - 날짜 별 , 조건 별 검색 컨트롤러, 매퍼, 서비스 추가

---

ks43team01/src/main/resources/templates/userpage/fragments/head.html

로그인 수정하기 위한 커밋

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/modifyNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html

2022-07-15 (10:43) qna board 조회수 증가

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/modifyQnaBoard.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/qnaBoardList.html

2022-07-15 (16:38) qnaBoard 페이징 처리

---

ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/static/assets/css/style.css
ks43team01/src/main/resources/templates/userpage/fragments/header.html
ks43team01/src/main/resources/templates/userpage/fragments/headerBackUp.html
ks43team01/src/main/resources/templates/userpage/reviewUser/modifyReview.html
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html
ks43team01/src/main/resources/templates/userpage/user/userinfomation.html

css 전면 수정 (리뷰, 헤더)

---

ks43team01/src/main/resources/application.properties
ks43team01/src/main/resources/mapper/GoodsMapper.xml

파일 첨부 설정 추가

---

ks43team01/src/main/java/ks43team01/mapper/BoardMapper.java
ks43team01/src/main/java/ks43team01/service/BoardService.java
ks43team01/src/main/java/ks43team01/user/controller/BoardController.java
ks43team01/src/main/resources/mapper/BoardMapper.xml
ks43team01/src/main/resources/templates/userpage/board/addFaqBoard.html
ks43team01/src/main/resources/templates/userpage/board/addNoticeBoard.html
ks43team01/src/main/resources/templates/userpage/board/faqBoardList.html
ks43team01/src/main/resources/templates/userpage/board/freeBoardList.html
ks43team01/src/main/resources/templates/userpage/board/noticeBoardList.html
ks43team01/src/main/resources/templates/userpage/search/boardSearch.html

2022-07-18 (16:37) qnaBoard 페이징, notice 검색 처리 추가

---

ks43team01/src/main/java/ks43team01/dto/ReviewContentsReg.java
ks43team01/src/main/java/ks43team01/mapper/ReviewMapper.java
ks43team01/src/main/java/ks43team01/service/ReviewService.java
ks43team01/src/main/java/ks43team01/user/controller/UserReviewController.java
ks43team01/src/main/resources/mapper/FileMapper.xml
ks43team01/src/main/resources/mapper/PointMapper.xml
ks43team01/src/main/resources/mapper/ReviewMapper.xml
ks43team01/src/main/resources/templates/userpage/reviewUser/addReview.html
ks43team01/src/main/resources/templates/userpage/reviewUser/reviewUserList.html

2022-07-18 리뷰 첨부파일 등록 기능 추가
